app:
  image: uptownhr/hackable
  volumes:
  - ./:/app
  - node_modules:/app/node_modules
  working_dir: /app
  command: npm run dev-docker
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/calendar
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=calendar.docker
  - NODE_ENV=development
mongo:
  image: mongo
redis:
  image: redis

webpack:
 build: ./webpack
 environment:
  - VIRTUAL_HOST=webpack.calendar.docker
  - ENV=dev
 volumes:
 - ./webpack:/webpack
 volumes_from:
 - app
